#!/usr/bin/bash

if [ $HOME != "/root" ]; then
	echo "please run me as root (or with sudo)!"
	exit 1
fi

function bincheck {
	packages=$@
	for package in $packages; do

		which $package > /dev/null
		if [ $? != 0 ]; then
			echo -e "\e[1;31mE\e[0m: $package is not installed"
			read -p "Install $package? [Y/n] " conf
			case "$conf" in
			y|Y|"" ) apt install $package;;
			n|N ) continue;;
			* ) echo "Invalid Option"; exit 1;;
			esac
		else
			echo -e "\e[1;34mI\e[0m: $package is already installed"
		fi
	done
}

# apt update
bincheck kitty micro zoxide zsh

# checks for scripts and other non-packages

## omz
if [ ! -d /home/$SUDO_USER/.oh-my-zsh ]; then
	echo -e "\e[1;31mE\e[0m: oh-my-zsh is not installed"
	read -p "Install oh-my-zsh? [Y/n] " conf
	case "$conf" in
	y|Y|"" ) sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ;;
	n|N ) :;;
	* ) echo "Invalid Option"; exit 1;;
	esac
else
	echo -e "\e[1;34mI\e[0m: oh-my-zsh is already installed"
fi

## powerlevel10k theme
if [ ! -f /home/$SUDO_USER/.p10k.zsh ]; then
	echo -e "\e[1;31mE\e[0m: powerlevel10k theme is not installed"
	read -p "Install powerlevel10k omz theme? [Y/n] " conf
	case "$conf" in
	y|Y|"" ) git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k;;
	n|N ) :;;
	* ) echo "Invalid Option"; exit 1;;
	esac
else
	echo -e "\e[1;34mI\e[0m: powerlevel10k theme is already installed"
fi


