#!/bin/bash

dryrun=false

while getopts ":hD" option; do
	case $option in
		h)  
			echo "Usage: livesync [-h] [-D] <command>"
            echo "Commands:"
            echo "  push     Push configurations to the repo"
            echo "  pull     Pull configurations from the repo"
            exit 0 ;;
		D) dryrun=true ;;
		?) echo "error: option -$OPTARG does not exist"; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

function copyconf {
	name=$1
	src=$2
	dst=$3

	# Look for config path
	# If its not found, get out of there!
	if [ ! -e $src ]; then
		echo "\e[1;31mE\[e[0m: $name config not found" | tee -a sync.log
		return 1
	fi

	# Looks like we're still here, copy the config
	echo "Copying $name config to $dst..." | tee -a sync.log
	# if the destination isn't found, make a directory
	# (this is kinda hacky and evil but i cant think of a better way rn :/)
	if [ ! -e $dst ]; then
		if $dryrun; then
			echo "Dryrun: Creating directory $dst"
		else
			mkdir -p $dst | tee -a sync.log
		fi
	fi

	# If the source is a directory, copy recursively and ignore git stuff
	if [ -d $src ]; then
		if $dryrun; then
			echo "Dryrun: Copying directory $src to $dst"
		else
			rsync -a -vv --exclude ".git*" $src $dst | tee -a sync.log
		fi
	# else, just copy it
	elif [ -f $src ]; then
		if $dryrun; then
			echo "Dryrun: Copying file $src to $dst"
		else
			rsync -vv $src $dst | tee -a sync.log
		fi
	fi
	echo -e "Done!\n" | tee -a sync.log
	return 0
}

gitdir=$(readlink -f $0 | sed "s/\/livesync//")

# Define config directories/paths
kittyconf="$HOME/.config/kitty/kitty.conf"
zshconf="$HOME/.zshrc"
omzconf="$HOME/.oh-my-zsh/"
p10kconf="$HOME/.p10k.zsh"
microconf="$HOME/.config/micro"
zoxidedb="$HOME/.local/share/zoxide/db.zo"

case $1 in
	"push") 
		copyconf "kitty" $kittyconf "$gitdir/configs/kitty/"
		copyconf "zsh" $zshconf "$gitdir/configs/zsh/"
		copyconf "oh-my-zsh" $omzconf "$gitdir/configs/oh-my-zsh"
		copyconf "p10k" $p10kconf "$gitdir/configs/p10k/"
		copyconf "micro" $microconf "$gitdir/configs/"
		copyconf "zoxide db" $zoxidedb "$gitdir/configs/zoxide/"
		if [ ! $dryrun ]; then
			git --git-dir $gitdir add "$gitdir/*" && git --git-dir $gitdir commit -a -m "Synced @ $(date)" && git --git-dir $gitdir push
		fi
		exit 0 ;;
		
	"pull")
		copyconf "kitty" "$gitdir/configs/kitty/" $kittyconf
		copyconf "zsh" "$gitdir/configs/zsh/" $zshconf
		copyconf "oh-my-zsh" "$gitdir/configs/oh-my-zsh" $omzconf
		copyconf "p10k" "$gitdir/configs/p10k/" $p10kconf
		copyconf "micro" "$gitdir/configs/" $microconf
		copyconf "zoxide db" "$gitdir/configs/zoxide/" $zoxidedb
		exit 0 ;;

	"")
		echo "Usage: livesync [-h] [-D] <command>"
        echo "Commands:"
        echo "  push     Push configurations to the repo"
        echo "  pull     Pull configurations from the repo"
        exit 0 ;;
	*)
		echo "Unknown command: $1"
		exit 1 ;;
esac
